### ISSUE TITLE
Portada

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#1]

**Comment by LEspadaC** [comment]
[prometheia.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654614/prometheia.pdf)

Aquí está la portada.

**Comment by iratxedominguez2** [comment]
Me flipa la portada Laura. <3

**Comment by LEspadaC** [comment]
Como me fio de tu criterio, y no creo que tenga más misterio el tema, cierro issue jajajaja ;)
