### ISSUE TITLE
Flyer.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#13]

**Comment by DanielOcasar** [comment]
![Flyer final](https://user-images.githubusercontent.com/72817171/101656165-b2fb5380-3a42-11eb-956a-c7b0d4bb9669.jpg)

**Comment by iratxedominguez2** [comment]
Ojo, te ha quedado mazo guay.

**Comment by LEspadaC** [comment]
Perfectísimo!!
