### ISSUE TITLE
Estudio de mercado.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#14]

**Comment by LEspadaC** [comment]
[analisis dafo.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654854/analisis.dafo.pdf)

**Comment by LEspadaC** [comment]
[situación de mercado.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654929/situacion.de.mercado.pdf)

**Comment by LEspadaC** [comment]
[usp.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5655185/usp.pdf)

**Comment by iratxedominguez2** [comment]
Laura, acabo de leer todo y me parece que está todo bastante completo.

**Comment by LEspadaC** [comment]
Genial, pues me espero a ver si contesta alguien más y si no cierro issue :)
