### ISSUE TITLE
Índice

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#2]

**Comment by LEspadaC** [comment]
[indice.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654526/indice.pdf)

**Comment by LEspadaC** [comment]
El índice se actualizará al final, cuando una todo

**Comment by iratxedominguez2** [comment]
Laura, la parte de derechos quítala porque no es necesaria.

**Comment by LEspadaC** [comment]
Entendido 👍

**Comment by LEspadaC** [comment]
Lo actualizo ya para el final, cierro este issue.
