### ISSUE TITLE
Derechos de autor y propiedad intelectual.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#28]
- [x] Indica qué elementos de vuestro juego estarán sujetos a algún tipo de protección, qué
tipo de licencia tienes pensado utilizar (copyright o copyleft) y por qué. 

- [x] Realiza un contrato ficticio con un Publisher.

**Comment by iratxedominguez2** [comment]
Os dejo por aquí el contracto ficticio.
[modelo_contrato_cesion_de_derechos_web.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5942455/modelo_contrato_cesion_de_derechos_web.docx)

**Comment by Iblaz** [comment]
Dejo aquí los derechos de autor y propiedad intelectual de los elementos de la obra: 
[Derechos de autor y propiedad intelectual.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6039591/Derechos.de.autor.y.propiedad.intelectual.docx)
