### ISSUE TITLE
Guión de una parte del juego con Twine.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#29]

**Comment by LEspadaC** [comment]
[Guión nivel 1 prometheia.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6055304/Guion.nivel.1.prometheia.pdf)

**Comment by LEspadaC** [comment]
En este guión, sacado de la construcción del primer nivel del GDD, se basará el guión de Twine

**Comment by LEspadaC** [comment]
[Nivel1_Prometheia.zip](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6056198/Nivel1_Prometheia.zip)

Aquí está el Twine, echadle un ojo y me comentáis si veis que falta algo

**Comment by LEspadaC** [comment]
![Estructura](https://user-images.githubusercontent.com/72516160/109406221-af0f0b80-7977-11eb-8718-9ae89f7c7506.PNG)

Para incluirlo en el pdf y se observe visualmente la estructura
