### ISSUE TITLE
Equipo humano

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#3]
Departamentos, roles y número de personas necesarias.

**Comment by Iblaz** [comment]
[Equipo Humano necesario.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654525/Equipo.Humano.necesario.docx)

**Comment by Iblaz** [comment]
He modificado la versión "in progress" que teníamos en el drive desde hace semanas y creo que ahora está completa. Revisarlo porfa, y la cerramos cuanto antes.

**Comment by iratxedominguez2** [comment]
Iván, lo he estado revisando. ¿No te faltaría el animador, el director financiero y un publisher/distribuidora? Que es lo que añadí aparte en mi apartado.

**Comment by Iblaz** [comment]
Los dos primeros sí, lo último es contratar a terceros, osea que yo lo considero un no.
Si no forma parte de la empresa no cuenta como equipo humano imagino.

**Comment by Iblaz** [comment]
Corrijo, lo del animador sobra, del equipo técnico también; no sé porqué ayer no lo pensé. Los sprites los hace el equipo de arte y la animación se monta automáticamente con código, esto no es 3D. Osea, que hay que quitarlo del Equipo técnico y de la tabla esa que hiciste.

**Comment by Iblaz** [comment]
[Equipo.Humano.necesario.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660454/Equipo.Humano.necesario.docx)

**Comment by Iblaz** [comment]
Corregido, falta quitar lo que te digo de lo tuyo. Perdona por no darme cuenta ayer.

**Comment by iratxedominguez2** [comment]
Vale, no pasa nada. Ya lo he corregido.

**Comment by LEspadaC** [comment]
Nada que añadir.
En cuanto cerreis issues voy juntandolos.
Una única duda, ¿lo de Arturo García García de la Torre es una errata?

**Comment by Iblaz** [comment]
No lo es. Te vale así o necesitas PDFs Laura, que me acabo de levantar.

**Comment by LEspadaC** [comment]
Así me vale. Muchas gracias :)
