### ISSUE TITLE
Producción del juego.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#31]

**Comment by Josusu** [comment]
[ProdruccionDelJuego.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6054236/ProdruccionDelJuego.pdf)
Subo el pdf de la producción del juego

**Comment by Josusu** [comment]
[ProdruccionDelJuego.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6054278/ProdruccionDelJuego.pdf)
Pdf-añadido un programa más que hemos usado
