### ISSUE TITLE
Post Mortem.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#34]

**Comment by iratxedominguez2** [comment]
Dejo por aquí los aspectos que he visto: 

ASPECTOS POSITIVOS
Idea original.

Hemos ampliado conocimientos sobre el Pixel Art y hemos descubierto nuevos programas que nunca antes hemos utilizado.

Es un nivel sencillo. Tiene un sistema de juego fácil y entendible.

Ya que es un juego que cuenta con varias referencias estéticas como Castlevania, va a atraer a jugadores amantes y nostálgicos de este tipo de juegos. Además, atraerá a gente amante del Pixel Art y de lo “retro” que tenga cierta nostalgia.

 Debido a que los temas principales son los ángeles y Nefilims, los apasionados de la mitología y fantasía se verán atraídos por nuestro videojuego.

Atraerá a los jugadores que amen el 2D y el scroll lateral.


ASPECTOS NEGATIVOS
No hemos podido incluir todo lo que habíamos pensado el año pasado.

No hemos plasmado la idea inicial que teníamos en mente.

No se entiende la utilidad de las diferentes armas ya que no se ha incluido el aspecto de los dos diferentes caminos.

El único objetivo del nivel es matar al enemigo, factor bastante simple.

La balanza de karma (elemento bastante significativo) no se ha incluido.

**Comment by LEspadaC** [comment]
**ACIERTOS**

Buena comunicación entre los miembros del equipo. Se consiguió llegar a tiempo a la mayoría de los hitos establecidos durante el kickoff.

Implicación y motivación por sacar el juego adelante a pesar de las dificultades que éste atravesaba.

Sprites y Escenarios muy bien realizados, así como su implementación.

Se consigue mantener la estética deseada tanto en la UI, como en los elementos y personajes, poseyendo todo una gran armonía y cohesión.

El juego es jugable. Simple y típico del género metroidvania. Para quien no supiera de las ideas que tuvieramos al principio que al final no pudimos implementar, como es el sistema de karma, podría jugarlo y disfrutarlo sin echar de menos esos elementos que pretendíamos que fueran distintivos.

**FALLOS**

Aspirábamos a mucho. No eramos conscientes de nuestras posibilidades y el tiempo que requería, ni del tiempo real del que disponíamos.

Los desarrolladores no estaban preparados, nos faltaba experiencia. Este proyecto nos ha servido para iniciarnos en el proceso de crear un videojuego, pero no para perfeccionarlo.

Falta de tiempo. Debido a la situación de pandemia, tuvimos un tiempo muy corto para poder realizar el videojuego. Así pues, del mismo modo, ese tiempo tuvo que usarse para compaginar otras asignaturas con proyectos igual de exigentes.

La jugabilidad es  muy simple: un sistema de plataformas con enemigos, sin ningún puzzle o elemento especial. Nada que ver con lo que teníamos en mente.

Durante todo el proceso no se llegaron a ultimar ciertos detalles sobre el juego, que estaban muy en el aire. No nos pusimos de acuerdo de la diferencia entre las dos armas. Sin embargo, tampoco pudimos incluir una diferencia real entre ellas a la hora de programarlo. Por lo que no resultó relevante.
