### ISSUE TITLE
Derechos de autor PRESENTACIÓN ORAL 

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#37]

**Comment by Iblaz** [comment]
De cara al apartado de derechos de autor de la presentación, utilizar contenido visual para la parte de las diapositivas y el resto del contenido expuesto será una explicación concisa de lo redactado en el apartado escrito.

**Comment by Iblaz** [comment]
Para revisar el contenido del que se hablará, remitirse a la otra issue de propiedad intelectual.

**Comment by Iblaz** [comment]
[Derechos de autor y propiedad intelectual ORAL.pptx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6041347/Derechos.de.autor.y.propiedad.intelectual.ORAL.pptx)
Versión de la diapositiva a falta de montado (no tiene pie ni cabezal precisamente por eso).
