### ISSUE TITLE
Lista de tareas.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#4]

**Comment by Iblaz** [comment]
Revísamelo, pero creo que con esto vale, es todo lo que se nos fue ocurriendo el día aquel.
[Lista de Tareas.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654720/Lista.de.Tareas.docx)

**Comment by Iblaz** [comment]
Si te parece bien lo dejamos así.

**Comment by iratxedominguez2** [comment]
Vale sí. Me parece perfecto.

**Comment by LEspadaC** [comment]
Muy completo, no veo que falte nada
