### ISSUE TITLE
Fase de Producción Diseño PRESENTACIÓN ORAL

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#40]

**Comment by DanielOcasar** [comment]
[Fase de Producción.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/6078579/Fase.de.Produccion.docx)

Esto es lo que tengo que decir, en plan que es pa tenerlo localizado en caso de que se me olvide imprimirlo o que haya algún problema , no lo tengáis en cuenta.

**Comment by DanielOcasar** [comment]
![Captura](https://user-images.githubusercontent.com/72817171/109860620-aad83c00-7c5e-11eb-9290-1d5731d031d9.PNG)
![Captura2](https://user-images.githubusercontent.com/72817171/109860621-ab70d280-7c5e-11eb-99fd-baf1d4a98378.PNG)
![WhatsApp Image 2020-12-20 at 15 46 57](https://user-images.githubusercontent.com/72817171/109860622-ac096900-7c5e-11eb-8ace-e050eac7d6e0.jpeg)
![WhatsApp Image 2021-01-16 at 01 55 56](https://user-images.githubusercontent.com/72817171/109860624-ac096900-7c5e-11eb-95a0-bab163b6f1c6.jpeg)
![WhatsApp Image 2021-01-17 at 14 23 34](https://user-images.githubusercontent.com/72817171/109860625-ac096900-7c5e-11eb-94b3-42dc1bf3fb6c.jpeg)

Estas son las imágenes que puedes meter para mi apartado, si puedes intenta meterlas todas en la misma pagina sabes? en plan para que esté todo junto y se pueda diferenciar mi punto que dentro de producción es el diseño, del punto de Josué que dentro de producción es programación. La de la barra de vida puedes quitar el fondo si quieres y ponerla en grande como quieras, eso ya como tu quieras ponerlo.
