### ISSUE TITLE
Fase de Producción Programación PRESENTACIÓN ORAL

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#41]

**Comment by Josusu** [comment]
![Captura](https://user-images.githubusercontent.com/73643418/109873406-fc3bf780-7c6d-11eb-96f9-180e05c191db.JPG)
![Captura2](https://user-images.githubusercontent.com/73643418/109873412-fe05bb00-7c6d-11eb-85d2-d5a9cef06904.JPG)
![Captura3](https://user-images.githubusercontent.com/73643418/109873414-ff36e800-7c6d-11eb-8a39-17fa1e6dc9ed.JPG)
![Captura4](https://user-images.githubusercontent.com/73643418/109873416-ff36e800-7c6d-11eb-92db-5dff0b9c1dee.JPG)
