### ISSUE TITLE
Fase de pruebas PRESENTACIÓN ORAL

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#42]

**Comment by pedrojm11** [comment]
imagenes para la presentacion



![Captura4](https://user-images.githubusercontent.com/72516362/109858551-41efc480-7c5c-11eb-8b9a-70a969b0995b.PNG)
![Captura5](https://user-images.githubusercontent.com/72516362/109858557-42885b00-7c5c-11eb-8148-2de878a1f3fa.PNG)
![Captura6](https://user-images.githubusercontent.com/72516362/109858561-42885b00-7c5c-11eb-8416-90540ada83a1.PNG)
