### ISSUE TITLE
Workflow.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#5]

**Comment by Iblaz** [comment]
Igual debí subirlo hace semanas, que lleva comiendo polvo demasiado.

**Comment by Iblaz** [comment]
![Workflow](https://user-images.githubusercontent.com/72516128/101390646-73f2c400-38c3-11eb-8911-5b4179b4f693.png)

**Comment by Iblaz** [comment]
Es un PNG, no se si con esto nos vale, si no simplemente lo monto en PDF y ale. Pero para definir el "Workflow", esto es lo más eficiente.

**Comment by Iblaz** [comment]
Por si acaso, Workflow en Word y en PDF
[Workflow en PDF.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654616/Workflow.en.PDF.pdf)
[Workflow en Word.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5654617/Workflow.en.Word.docx)

**Comment by iratxedominguez2** [comment]
A mi así me parece muy visual y creo que está bien.

**Comment by LEspadaC** [comment]
Me gusta que no sea además los típicos cuadraditos y esté decorado jajaja. 💯
