### ISSUE TITLE
Diagrama de Gantt.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#6]

**Comment by Iblaz** [comment]
PDF: 
[Gantt Prometheia.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5661845/Gantt.Prometheia.pdf)

Imágenes:
![Gantt Prometheia](https://user-images.githubusercontent.com/72516128/101539678-306d8800-399f-11eb-846f-46c4dcc3f76c.png)
![Gantt Prometheia res](https://user-images.githubusercontent.com/72516128/101539681-32374b80-399f-11eb-9eb7-7ccedfa64522.png)

El archivo de proyecto:
(Pincha en URL y descarga)
https://drive.google.com/file/d/14QAaN-R8RSqlqjbIJtcq7M1k4I3pafGa/view?usp=sharing

**Comment by Iblaz** [comment]
Ni caso a lo anterior, aquí renovados.

**Comment by Iblaz** [comment]
PDF: 
[Gantt Prometheia.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5662313/Gantt.Prometheia.pdf)
Imágenes:
![Gantt Prometheia res](https://user-images.githubusercontent.com/72516128/101549014-34080b80-39ad-11eb-90e8-21f7008e2cc7.png)
![Gantt Prometheia](https://user-images.githubusercontent.com/72516128/101549016-34a0a200-39ad-11eb-8ec1-20cf2cdcdb8f.png)
Proyecto:
(Click a la URL)
https://drive.google.com/file/d/14QAaN-R8RSqlqjbIJtcq7M1k4I3pafGa/view?usp=sharing

**Comment by LEspadaC** [comment]
Perfecto 👍 👍 
Que te de alguien más el visto bueno y se cierra
