### ISSUE TITLE
Equipo técnico.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#7]

**Comment by iratxedominguez2** [comment]
[EQUIPO TECNICO PRESUPUESTO.docx](https://github.com/alhgo/Prometheia/files/5631453/EQUIPO.TECNICO.PRESUPUESTO.docx)

**Comment by Iblaz** [comment]
He revisado el documento de cara a realizar el gantt y lo que acordamos del equipo humano. He cambiado alguna que otra cosa que en mi opinión estaba mal (como el apartado de concept art, lo nuestro no son concepts, son diseños).
Revísamelo y dime que te parece.

**Comment by Iblaz** [comment]
[EQUIPO.TECNICO.PRESUPUESTO.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5652618/EQUIPO.TECNICO.PRESUPUESTO.docx)

**Comment by Iblaz** [comment]
Si te gusta cierra el issue.

**Comment by iratxedominguez2** [comment]
Vale, lo he revisado y he corregido alguna cosa que me fallaba.
[EQUIPO.TECNICO.PRESUPUESTO.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5653643/EQUIPO.TECNICO.PRESUPUESTO.docx)

**Comment by iratxedominguez2** [comment]
[TABLA TOTAL PRESUPUESTO.docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5653753/TABLA.TOTAL.PRESUPUESTO.docx)

**Comment by Iblaz** [comment]
Lo de los dos meses de los artistas te has cebado. Mínimo 4, que es una parte muy grande del desarrollo.

**Comment by iratxedominguez2** [comment]
En mi opinión, en nuestro grupo ya hay bastantes artistas. Tenemos 3, por eso he puesto 2 meses a la gente de fuera. Nada más.

**Comment by Iblaz** [comment]
No si no veo mal ser optimista. Pero es que escucha, que se tiene que hacer el diseño de todas las salas de varios niveles, y ponte que cada nivel tiene fácil 40 salas. Más otros tantos aspectos técnicos en los que tienen que trabajar casi a la vez.

**Comment by Iblaz** [comment]
Osea, dices 2 meses para los 2 extras, y el resto que siga continuando con el desarrollo a lo largo de la duración del proyecto¿?

**Comment by iratxedominguez2** [comment]
Exacto, que los dos extra nos ayuden durante dos meses y luego seguir con Josué, Dani y Pedro.

**Comment by Iblaz** [comment]
Entonces vale, es que no lo entendí así.

**Comment by Iblaz** [comment]
Si te convence cierra el issue.

**Comment by iratxedominguez2** [comment]
DOCUMENTOS CORREGIDOS
[TABLA.TOTAL.PRESUPUESTO (2).docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660794/TABLA.TOTAL.PRESUPUESTO.2.docx)
[EQUIPO.TECNICO.PRESUPUESTO (6).docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660795/EQUIPO.TECNICO.PRESUPUESTO.6.docx)

**Comment by iratxedominguez2** [comment]
DOCUMENTOS CORREGIDOS
[TABLA.TOTAL.PRESUPUESTO (2).docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660801/TABLA.TOTAL.PRESUPUESTO.2.docx)
[EQUIPO.TECNICO.PRESUPUESTO (6).docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660802/EQUIPO.TECNICO.PRESUPUESTO.6.docx)

**Comment by iratxedominguez2** [comment]
DOCUMENTOS CORREGIDOS
[EQUIPO.TECNICO.PRESUPUESTO.6 (1).docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660811/EQUIPO.TECNICO.PRESUPUESTO.6.1.docx)
[TABLA.TOTAL.PRESUPUESTO (2).docx](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5660812/TABLA.TOTAL.PRESUPUESTO.2.docx)

**Comment by LEspadaC** [comment]
Acabo de ver el archivo de  equipo técnico, y me parece que está bien :) 👍

**Comment by LEspadaC** [comment]
Pero por otro lado, la "tabla total de presupuesto" al ser formato docx no me deja verla completa en wordpad y no tengo el paquete office. Subemela en pdf plisu así la puedo ver para juntarlo luego todo. 

Cuando la vea ya te doy el visto bueno y cerramos issue

**Comment by iratxedominguez2** [comment]
[TABLA.TOTAL.PRESUPUESTO.2.pdf](https://github.com/CIFP-Jose-luis-Garci/Prometheia/files/5664581/TABLA.TOTAL.PRESUPUESTO.2.pdf)
