### ISSUE TITLE
Local y mobiliario.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#8]

**Comment by Josusu** [comment]
[PRESUPUESTO_local_mobiliario.docx](https://github.com/alhgo/Prometheia/files/5603987/PRESUPUESTO_local_mobiliario.docx)

**Comment by LEspadaC** [comment]
Josue, no se si has incluido algo más y no lo he podido visualizar. Tipo alguna tabla o algo así. 
Solo veo lo siguiente:

"- Local en la calle Hermanos Machado en Ventas, Madrid. Tiene 80m2, dos plantas y el alquiler son 550 euros al mes. https://www.idealista.com/inmueble/91880468/
- Mesas Linnmon/adils de 150x75cm a 39 euros, se comprarían el mismo número de mesas que de trabajadores. https://www.ikea.com/es/es/p/linnmon-adils-mesa-blanco-efecto-roble-tinte-blanco-negro-s19215675/
- Compraríamos los ordenadores por componentes en PcComponentes y deberían estar cada uno por los 1000 euros. Puede que un poco más barato si los montasemos nosotros mismos. "

Si hay algo más, súbelo en pdf para que pueda verlo porfi, que si no no lo voy a poder meter en el documento final
