### ISSUE TITLE
Material técnico.

### ISSUE THREAD

**Issue by iratxedominguez2** [CIFP-Jose-luis-Garci/Prometheia#9]

**Comment by Josusu** [comment]
[PRESUPUESTO_materialTecnico.docx](https://github.com/alhgo/Prometheia/files/5603988/PRESUPUESTO_materialTecnico.docx)

**Comment by LEspadaC** [comment]
Visto 👍  Lo único, lo que he avisado por el grupo. Si has incluido una tabla o algún elemento gráfico súbemelo en pdf para que pueda visualizarlo y juntarlo :)
